name: Deploy Backend

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Package Backend Code Modules
        run: |
          mkdir -p code_artefacts

          for file in backend_code/*; do
            relative_file=$(basename "$file")
            zip -r "code_artefacts/$relative_file.zip" "$file"
          done

      - name: Generate tfvars
        run: |
          cat > aws_backend/terraform.tfvars <<- EOF
          deployment_info = {
            project_name = ""{{ env.PROJECT_NAME }}",
            environment = "${{ env.ENVIRONMENT }}",
            region = "${{ env.AWS_REGION }}",
          }
          code_artefacts_path = "${{ github.workspace }}/code_artefacts"
          EOF

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@v0.2.1
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "aws_backend"
          tf_actions_backend_config: |
              bucket = "${{ secrets.TF_STATE_BUCKET }}"
              key    = "${{ secrets.TF_STATE_KEY }}"
              region = "${{ secrets.TF_STATE_REGION }}"

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@v0.2.1
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "aws_backend"
          tf_actions_plan_arguments: "-out=tfplan -var-file=terraform.tfvars"

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@v0.2.1
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: "aws_backend"
          tf_actions_plan_arguments: "tfplan"
