name: "[Dev] Deploy AWS Backend"

on:
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy_aws_backend.yml
    with:
      environment: Dev
    secrets: inherit
